### ISSUE TITLE
SpeechSynthesisWordBoundaryEvent has text_offset set to 4294967295

### ISSUE THREAD

**Issue by tuzz** [jabber-tools/cognitive-services-speech-sdk-rs#24]
When synthesizing the following SSML:

```xml
<speak version="1.0" xml:lang="en-GB">
  <voice name="en-GB-SoniaNeural">
    <sub alias="a">b</sub>
  </voice>
</speak>
```

A word boundary event is emitted with a text offset set to u32 max value:

> [2024-09-23T14:38:11Z INFO  synthesizer::helpers] >set_synthesizer_word_boundary_cb SpeechSynthesisWordBoundaryEvent { handle: SmartHandle { inner: 0x600002be4000, release_fn: 0x1048b5498, name: "SpeechSynthesisWordBoundaryEvent" }, audio_offset: 500000, duration_ms: 4250000, text_offset: **4294967295**, word_length: 4, boundary_type: WordBoundary }

This seems like a bug. Is the underlying SDK setting the value to -1? Should these events be discarded? Thanks

**Comment by tuzz** [comment]
After investigating, the text_offset is set to -1 (u32::MAX) if the event's text doesn't exactly match the input SSML. For example, if the event's text is "cat's" and the input SSML contains "cat&apos;s". The Python SDK returns `text_offset: -1` in this case but it also returns the text so it's less of an issue.

**Comment by adambezecny** [comment]
this was already addressed within https://github.com/jabber-tools/cognitive-services-speech-sdk-rs/pull/25
